### ISSUE TITLE
getActivity() null

### ISSUE THREAD

**Issue by Shakezulla57** [miquelbeltran/conductor-viewmodel#10]
Hi Miquel

Thanks again for the useful library. I'm curious if you've run into this issue. Every now and then we get a crash on line 30 of the `ViewModelController` class.

```
public ViewModelProvider viewModelProvider() {
        return this.viewModelProvider(new AndroidViewModelFactory(this.getActivity().getApplication()));
    }
```

Somehow `getActivity()` is returning null.

We're instantiating our `ViewModel` in the `onCreateView` of our Controller. Some things to not about this controller: its in a childrouter and we're using `RetainViewMode.RETAIN_DETACH`.

Now as I've been going through the code to write up this issue I notice it uses `AndroidViewModelFactory` which to my understanding is used to provide a `ViewModel` that has access to a `Context`.  I don't a `Context` in this `ViewModel`, could using just `NewInstanceFactory` possibly solve this problem?

Thanks

**Comment by miquelbeltran** [comment]
Hi! To be honest I never saw that issue (and I've been using this library in production).

No idea why `getActivity()` may be null in the `onCreateView` of a Conductor's Controller.

But yes, you can use one of the other `viewModelProvider` methods that allows you to pass a ViewModel factory as parameter, so you can pass your own.

**Comment by miquelbeltran** [comment]
archiving project
