### ISSUE TITLE
ControllerLifecycleOwner discrepancies

### ISSUE THREAD

**Issue by mradzinski** [miquelbeltran/conductor-viewmodel#2]
Hi @miquelbeltran, any reasons why your `ControllerLifecycleOwner` class has discrepancies with the one provided by Erick on the Conductor's repo? Not complaining, just wondering out of curiosity. You can check the "official" one [here](https://github.com/bluelinelabs/Conductor/blob/develop/conductor-modules/arch-components-lifecycle/src/main/java/com/bluelinelabs/conductor/archlifecycle/ControllerLifecycleOwner.java).

Cheers and thanks!

**Comment by miquelbeltran** [comment]
Yes, there's a reason, I have a comment about that on the FAQ of the README.md:

> Why is the ON_DESTROY event in onDestroyView?
> In order to remove the observers from the LiveData when the view is destroyed.

IMO the "official" doesn't work as expected with a LiveData from Architecture Components. In the case of the "official" one, the `LiveData` observers will still be subscribed even after a configuration change. So if you are observing `LiveData` in your `onCreateView` methods, that means you will have a new observer each time the view is recreated.

In the "official" one, the `LiveData` observers will only stop observing once the Controller is destroyed.

IMO: LiveData observers should rely on the View lifecycle and not on the Controller lifecycle. But I see a use-case for the other case too! So probably the right solution is to have a `lifecycleRegistry` for the View LifeCycle and a `lifecycleRegistry` for the Controller lifecycle.

I am not saying that the official one is wrong, rather that it does not work as supposed for LiveData.

I hope my explanation is somehow clear!

**Comment by mradzinski** [comment]
Yep, pretty clear @miquelbeltran. 

> So probably the right solution is to have a lifecycleRegistry for the View LifeCycle and a lifecycleRegistry for the Controller lifecycle.

How can that be achieved? AFAIK implementing `LifecycleOwner` will allow you to provide one `lifecycleRegistry` 😕

**Comment by miquelbeltran** [comment]
very good point!

I think it is possible to pass the `LifecycleOwner` to the `LiveData.observe` call, in that case you will have to pass the "view" lifecycle one. It's a bit tricky to handle but possible to have two different LifecycleOwners, one for the View and one for the Controller, and use the one for the view in the `observe` call.

**Comment by mradzinski** [comment]
I get your point, but unless I'm missing something then it's sort of tricky given that we're talking about a single class which can't implement `LifecycleOwner` twice, so I think it's either your implementation or Erick's one. The only solution I can think of right now is to have two completely different kind of Controllers, one with your implementation (in case of using LiveData) and another type of Controller following Erick's impl. But can't think of how mixing both into one single Controller and use them as needed.

Let's not forget `LiveData.observe` accepts a class implementing `LifecycleOwner` and not a `lifecycleRegistry`.

**Comment by miquelbeltran** [comment]
> Let's not forget LiveData.observe accepts a class implementing LifecycleOwner and not a lifecycleRegistry.

You can do the following:

```
        viewModel.getData().observe({ lifecycleRegistry }, { liveDataValue ->
            // use the LiveData here
        })
```

The LifecycleOwner is an interface with a single method `getLifecycle(): Lifecycle`, and `LifecycleRegistry` extends `Lifecycle`. I know it is not the nicest API but it is doable and Kotlin makes it easier 😄 

I think you could have a secondary `LifecycleRegistry` besides the one from the superclass.

Again, not the nicest API, but I think it is doable.

**Comment by mradzinski** [comment]
@miquelbeltran Makes total sense. You can actually have it be a Kotlin extension too, which would make it much more easy. Something like `LiveData.observe(lifecycleRegistry, observer)`.

The more I think about it, the more reasonable it sounds. If would love making a PR for this, but since your project is written in Java I can't make the extensions. If at some point you move it to Kotlin and find some interest into bringing both implementations (your's and Erick's) together ping me here on this issue and I'll PR it for you.

I'll close this, there's enough context and info for anyone to figure out the differences and how to unify both approaches.

Cheers and thanks a ton!
