### ISSUE TITLE
Add example with Koin 2.0

### ISSUE THREAD

**Issue by miquelbeltran** [miquelbeltran/conductor-viewmodel#7]
In theory, Koin 2.0 will support having a custom ViewModelProvider (and not forcing you to use Activity or Fragment) which will allow to use Koin's `by viewModel()`.
I'd love if someone can verify this and provide some sample code, even in the README.md or in the app demo code.
Thank you!

**Comment by larten** [comment]
+1

**Comment by larten** [comment]
I extender your ViewModelController with ViewModelStoreOwner and I'm trying with this, but in the ViewModelResolution the parameters.from is null :S
`val vm: Feature1ViewModel by viewModel(parameters = { parametersOf(ViewModelParameters(owner = this, from = { this }, clazz = ViewModelController::class, scope = Scope("xyz"))) })`

**Comment by mario** [comment]
Any progress on this maybe?

**Comment by miquelbeltran** [comment]
I am not maintaining the project, but if anyone wants to do this, feel free. That's why there's a [help wanted] label on it.

**Comment by miquelbeltran** [comment]
archiving project
